alias ll='ls -al --color=auto'
alias untar='tar -zxvf '
alias ping='ping -c 5'
alias cls='clear'
alias c='clear'
alias ls='ls --color=auto'
alias mkdir='mkdir -pv'
alias ports='netstat -tulanp'
#alias rm='rm -I --preserve-root'
alias wget='wget -c'
alias ..='cd ..'
alias dc='docker compose'
