#!/bin/sh
while getopts t:i: option
do 
    case "${option}"
        in
        t)
            type='new'
            title=${OPTARG}
            break
            ;;
        i)
            type='existing'
            issue_id=${OPTARG}
            break
            ;;
    esac
done

if [[ $type != 'new' && $type != 'existing' ]]; then
    echo 'Please specify either -t or -i'
    exit 1
fi

if [ $type == 'new' ]
then
    echo "Creating new issue with title: $title"
    # glab issue create --title 'Trekk ut query params i AnswerAccessibilityViewParam' --description '' --label 'team::kp,status::in progress' | cat
    output=$(glab issue create --title "$title" --label "team::kp,status::ready" --description "")

    # Example output:
    # - Creating issue in feide/feide-kp
    # https://gitlab.sikt.no/feide/feide-kp/-/issues/3796
    echo "$output"
    issue_id=$(echo "$output" | awk '/issues\/(.*)/' | awk -F'/' '{print $NF}' | xargs)
    echo "Parsed issue id $issue_id"
fi
echo "Ready to initiate work on issue $issue_id"

if [[ -z $issue_id ]]
then
    echo 'No issue id specified'
    exit 1
fi

echo 'Creating MR for issue'
mr_output=$(glab mr create -a eiand --related-issue $issue_id --fill --yes)
# Example output:
# Creating draft merge request for 3798-trekk-ut-query-params-i-activationsapiviewparam-1 into master in feide/feide-kp
# https://gitlab.sikt.no/feide/feide-kp/-/merge_requests/3282
echo "$mr_output"
mr_id = $(echo "$mr_output" | awk '/merge_requests\/(.*)/' | awk -F'/' '{print $NF}' | xargs)
echo "Parsed MR id $mr_id"

echo 'Updating issue status'
glab issue update $issue_id -l "status::in progress" -a eiand

if [[ -z $mr_id ]]
then
    echo 'No MR id – cancelling checkout'
    exit 1
fi

echo 'Checking out MR branch'
glab mr checkout $mr_id