#!/bin/sh
if [ $# -ne 0 ]; then
  echo "This command accepts no arguments. Did you mean to run 'glab-start' instead?"
  exit 1
fi

mr_id=$(glab mr view | awk '/number:(.*)/' | awk -F':' '{print $2}' | xargs)
issue_id=$(glab mr view | awk '/Closes #(.*)/' | awk -F'#' '{print $2}' | xargs)
url=$(glab mr view | awk '/url:(.*)/' | awk '{print $2}' | xargs)
glab mr update --ready
glab issue update $issue_id -l "status::review"
echo ''
echo $url
echo $url | pbcopy
echo 'Copied MR URL to clipboard'